### ISSUE TITLE
Add core packages

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#5]
Roadmap to integrate core packages

### Stage 1
- [x] eslint-config `@verdaccio/eslint-config`
- [ ] babel-preset `@verdaccio/babel-preset`

### Stage 2
- [x] streams `@verdaccio/streams`
- [x] file-lock `@verdaccio/file-lock`
- [x] types `@verdaccio/types`
- [ ] http-error `@verdaccio/http-error`

### Stage 3

- [ ] local-storage `@verdaccio/local-storage`
- [ ] htpasswd-auth `@verdaccio/htpasswd-auth` (I'd suggest this renaming, but we can discuss it) cc: @ayusharma 

After Phase 1 some packages should be published to be integrated into Stage 2 packages https://github.com/verdaccio/core/issues/9, if all goes well we should move to Phase 2, we repeat the process integrating Stage 1,2 packages into Stage 3, if all goes well we will move Stage 3 into core packages.

All packages tagged as @sergiohgz described here https://github.com/verdaccio/core/issues/8#issuecomment-427510970 with `(v4.0.0-alpha.0?).`

### Final Stage

- [ ] Migrate all core packages into Verdaccio main project

**Comment by sergiohgz** [comment]
Hi @juanpicado, are you still working on this?

I think we have to talk about how to migrate repositories to monorepo and ensure we can make a complete flow before deprecating the old repositories.

**Comment by sergiohgz** [comment]
I'm closing this as we have updated information in #13
